### ISSUE TITLE
Game crash when hovering over Aged crate on pre1.20.6

### ISSUE THREAD

**Issue by hladislav** [kathanon/VintageStory-ImprovedHandbookRecipes#2]
To reproduce go to Parchment recipes and hover over Aged crate. Worked every time on both Linux and Windows.
1.19.8 works fine
Log:
```
Running on 64 bit Linux (Zorin OS 17.2) [Kernel 6.8.0.48] with 15907 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
11/3/2024 10:34:19 PM: Critical error occurred
Loaded Mods: emotemenureload@1.0.5, game@1.20.0-pre.6, vtr@4.0.5, egocaribautomapmarkers@3.1.0, commonlib@2.5.0-rc.2, farmlanddropssoil@1.4.0, hit@2.1.2, improvedhandbookrecipes@1.0.0, mif@1.0.1, minimalcompass@1.0.0, nbcartographer@2.0.10, prospecttogether@1.4.0-rc.2, creative@1.20.0-pre.6, vsimgui@1.1.5, vsinstruments@1.2.7, survival@1.20.0-pre.6, configlib@1.3.13, playercorpse@1.10.1-rc.1
Involved Harmony IDs: improvedhandbookrecipes
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Vintagestory.GameContent.CrateProperties.get_Item(String type) in VSSurvivalMod\Block\BlockCrate.cs:line 44
   at Vintagestory.GameContent.CollectibleBehaviorBoatableCrate.GetQuantitySlots(ItemStack bagstack) in VSSurvivalMod\Block\BlockCrate.cs:line 188
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch1(CollectibleObject this, ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2277
   at Vintagestory.GameContent.BlockContainer.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockContainer.cs:line 263
   at Vintagestory.GameContent.BlockCrate.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockCrate.cs:line 688
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Common.ItemSlot.GetStackDescription(IClientWorldAccessor world, Boolean extendedDebugInfo) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 476
   at Vintagestory.API.Client.ItemstackComponentBase.OnRequireInfoText(ItemSlot slot) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 62
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.OnRequireInfoText(ItemSlot slot) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowItemstackTextComponent.cs:line 178
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 125
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemSlot slot, Double renderX, Double renderY, Single dt) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 79
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 484
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 718
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 389
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI_Patch1(GuiDialogHandbook this, Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by hladislav** [comment]
Looks like the issue was in the base game, it was mentioned in [patch notes](https://info.vintagestory.at/v1dot20#pre7)
